# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rspec", "~> 3.13", :group => :test

gem "rubocop", "~> 1.81", :groups => [:development, :test]

gem "rubocop-rspec", "~> 3.8", :groups => [:development, :test]
